image: barichello/godot-ci:3.2.2

variables:
  EXPORT_NAME: Megamark

stages:
  - export
  - deploy

windows:
  stage: export
  script:
    - mkdir -v -p build/windows
    - godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/windows

macOS:
  stage: export
  script:
    - mkdir -v -p build/macOS
    - godot -v --export "Mac OSX" ./build/macOS/$EXPORT_NAME.dmg
  artifacts:
    name: $EXPORT_NAME-$CI_JOB_NAME
    paths:
      - build/macOS

pages:
  stage: deploy
  dependencies:
    - web
  script:
    - rm -rf public
    - cp -r build/web public
  artifacts:
    paths:
      - public
  only:
    - develop