name: Build/Export Megamark

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  export_game:
    runs-on: ubuntu-latest
    name: export megamark
    steps:
    - name: checkout
      uses: actions/checkout@v2.0.0
    - name: export
      uses: firebelley/godot-export@v1.1.0
      run: |
        echo "test debug"
        pwd
      with:
        base_version: 0.1.0
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_linux_headless.64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz
        godot_template_version: 3.2.3.stable
        relative_project_path: ./
      env:
        GITHUB_TOKEN: ${{ secrets.EXPORT_GITHUB_TOKEN }}

