on:
  release:
    types: [created, edited]

jobs:
  release_windows:
    runs-on: ubuntu-latest
    steps:
      - name: download windows
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: plague-windows.zip
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: release windows
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: megamark
          ITCH_USER: reydev
          PACKAGE: megamark-windows.zip